language: scala
scala: 2.10.2
before_install:
  - git submodule update --init --recursive
install:
  - sbt update
script:
  - ./nightly.sh --noclean

notifications:
  irc:
    channels:
      - "irc.freenode.org#netlogo"
    skip_join: true
    template:
      - "\x0313NetLogo\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
