name: package-windows

on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  package:
    runs-on: windows-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.HELIO_TOKEN }}

      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17.0.2
          java-package: jdk+fx
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - name: Install ImageMagick
        run: winget install ImageMagick.Q16-HDRI --accept-package-agreements --accept-source-agreements --disable-interactivity

      - uses: actions/setup-node@v5
        with:
          node-version: 23
          cache: npm
          cache-dependency-path: netlogo-gui/colorpicker/package-lock.json

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            spatstat@3.4-0
            rjson@0.2.23
            vegan@2.7-1

      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip3 install numpy
          pip3 install scikit-learn

      - uses: microsoft/setup-msbuild@v2

      - name: Install WiX
        run: |
          dotnet tool install --global wix
          wix extension add -g WixToolset.UI.wixext

      - name: Setup Packaging Environment
        run: |
          "- vendor: 'OpenJDK'" > .jdks.yaml
          "  version: '17.0.2'" >> .jdks.yaml
          "  architecture: '64'" >> .jdks.yaml
          "  path: '${{ env.JAVA_HOME }}'" >> .jdks.yaml

      - name: Build and Package NetLogo
        run: |
          sbt dist/buildNetLogo
          sbt "dist/packageWinAggregate OpenJDK_17.0.2_64"

      - uses: actions/upload-artifact@v6
        with:
          name: windows-64
          path: dist/target/downloadPages/*
          if-no-files-found: error
          overwrite: true

      - uses: actions/cache@v5
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
